name: Pruba DevSecOps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --no-cache-dir --upgrade -r requirements.txt   
    - name: Pruebas_Unitarias
      run: |
        python -m unittest discover tests
        
    - name: Analisis de codigo static
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username:  ${{ secrets.DOCKERHUB_USERNAME }}
        password:  ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ccastano12/devcofastapi:latest

